from django.conf.urls import url
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='Home'),
    url(r'^accounts/',include('allauth.urls')),
    path('tours/', views.tours, name='Tours'),
    path('fb-login/', views.fblogin, name='Fb-Login'),
#    path('user-profile/', views.user_profile, name='User-Profile'),
    path('access-denied/', views.access_denied, name='Access-Denied'),
    path('something-wrong/', views.something_wrong, name='Something-Wrong'),
    path('organizer/dashboard/create-event/', views.addEvent, name='Add Event'),
    path('tour/detail/<id>', views.tourDetail, name='Tour-Details'),
    path('tour/delete/<id>', views.deleteEvent, name='Delete Event'),
    path('tour/event/toggle/<id>', views.toggle_isFull, name='Toggle isFull'),
    path('tour/booking/toggle/<id>', views.toggle_isVerified, name='Toggle isVerified'),
    path('booking/delete/<id>', views.deleteBooking, name='Tour-Details'),
    path('organizer/detail/<id>', views.organizerDetail, name='Organizer-Detail'),
    path('organizer/portfolio/<id>', views.organizerPortfolioUser, name='Organizer-Detail'),
    path('login/', views.login, name='Login'),
    path('logout/', views.logout, name='Logout'),
    path('user/register/', views.signUp, name='Signup'),
#    path('organizer/register/', views.signUpOrganizer, name='Signup'),
    path('specialEvent/', views.specialEvent , name='specialEvent'),
    path('tips/', views.tips , name='tips'),
    path('faq/', views.faq , name='faq'),
    path('user/dashboard/event-booking/', views.userEventBooking , name='User Event Booking'),
    path('user/dashboard/event-bookings/', views.fbUserEventBooking , name='FBUser Event Booking'),
    path('organizer/dashboard/event-bookings/', views.OrganizerEventBooking , name='Organizer Event Booking'),
    path('user/dashboard/my-profile/', views.userMyProfile , name='User Profile'),
    path('organizer/dashboard/my-profile/', views.organizerMyProfile , name='Organizer Profile'),
    path('organizer/dashboard/portfolio/', views.organizerPortfolio , name='Portfolio'),
    path('organizer/dashboard/portfolio/add-photos', views.organizerAddPhotos , name='Event-photos'),
    path('organizer/dashboard/events/', views.organizerMyEvents , name='OrganizerEvents'),
    path('contact/',views.contact, name='Contact'),
    path('404/',views.not_found, name='404'),
    path('about/',views.about, name='About'),
    path('price-list/',views.price_list, name='Price-Lists'),
    path('organizer/register/',views.organizerSignUp, name='org-signUp'),
    path('forgot-pass/', views.forgotPassword,name='forgot-password'),
    path('email-forgot-pass/', views.EmailforgotPassword,name='forgot-password'),
    path('book-event/<id>', views.book_event,name='Book Event'),
    path('organizer/events/bookings', views.organizerEventBookings,name='Book Event'),
    path('organizer/event/schedule/<id>', views.organizerEventSchedule, name='Event Schedule'),
    path('organizer/event/questions/<id>', views.organizerEventQuestions, name='Event Questions'),
    path('organizer/events/<id>', views.userOrganizerEvents, name='Event Questions'),
    path('chat/', views.chat, name='Event Questions'),
]