# Generated by Django 3.0.1 on 2020-02-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_no', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('password', models.CharField(max_length=50)),
                ('userType', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('organizer_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organizer')),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
