# Generated by Django 3.0.1 on 2020-02-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_blocked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
