# Generated by Django 3.0 on 2020-03-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sessionlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionLogin',
        ),
    ]
