# Generated by Django 3.0.1 on 2020-02-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200220_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='userType',
            new_name='user_type',
        ),
    ]
