# Generated by Django 3.0.1 on 2020-02-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200220_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='organizer_ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Organizer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
