# Generated by Django 3.0.1 on 2020-02-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200220_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='organizer_ID',
            new_name='organizer',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='user_ID',
            new_name='user',
        ),
    ]
