# Generated by Django 3.0.1 on 2020-02-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200225_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='cnic',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
