# Generated by Django 3.0.1 on 2020-03-17 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_blockrequest_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockrequest',
            name='sentBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockrequest',
            name='sentFor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestFor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sentBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageSender', to=settings.AUTH_USER_MODEL)),
                ('sentFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessageReceiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('date_of_departure', models.DateTimeField()),
                ('date_of_arrival', models.DateTimeField()),
                ('slots', models.IntegerField()),
                ('is_accomodation', models.BooleanField(default=False)),
                ('is_food', models.BooleanField(default=False)),
                ('accomodation_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('food_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='api.Organizer')),
            ],
        ),
    ]
