# Generated by Django 3.0 on 2020-03-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200324_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
