# Generated by Django 3.0 on 2020-03-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
