# Generated by Django 3.0 on 2020-03-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200324_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='day',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
