# Generated by Django 3.0 on 2020-03-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_eventschedule_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionLogin',
        ),
    ]
