# Generated by Django 3.0 on 2020-03-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200328_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
