# Generated by Django 3.0 on 2020-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200319_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_of_arrival',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_departure',
            field=models.DateTimeField(null=True),
        ),
    ]
