# Generated by Django 3.0 on 2020-03-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200319_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.Event'),
        ),
    ]
