# Generated by Django 3.0 on 2020-05-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='organizer',
        ),
    ]
