# Generated by Django 3.0 on 2020-03-20 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200320_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_sightseeing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='sightseeing_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Organizer'),
        ),
    ]
