# Generated by Django 3.0 on 2020-03-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200320_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(null=True, upload_to='uploads/events/'),
        ),
    ]
