# Generated by Django 3.0 on 2020-06-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200610_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='organizer',
        ),
    ]
