# Generated by Django 3.0 on 2020-06-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_answer_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='person.png', null=True, upload_to='uploads/users'),
        ),
    ]
