# Generated by Django 3.0 on 2020-06-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200610_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='organizer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer1', to='api.Organizer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='api.User'),
        ),
    ]
