# Generated by Django 3.0 on 2020-06-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200610_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
