# Generated by Django 3.0 on 2020-06-13 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_review_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='organizer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.Organizer'),
        ),
    ]
