# Generated by Django 3.0 on 2020-06-13 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_review_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Organizer'),
        ),
    ]
