# Generated by Django 3.0 on 2020-06-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20200613_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default='New Booking', max_length=100),
        ),
    ]
