# Generated by Django 3.0 on 2020-06-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_verified',
            field=models.BooleanField(default=None),
        ),
    ]
